package hexagonal_architecture_go_template

const SCAN_PROJECT_NAME = "Project name (cannot be empty)"
const SCAN_VERSION = "Version [0.1.0]"
const DEFAULT_VERSION = "0.1.0"
const SCAN_DESCRIPTION = "Description"
const DEFAULT_DESCRIPTION = ""
const SCAN_REACT = "Generate frontend (React) skeletons [Y/n]"
const DEFAULT_ACTIVE = "y"
const DEFAULT_INACTIVE = "n"
const SCAN_SQL_DATABASE = "Add SQL database [Y/n]"
const SCAN_MYSQL = "Add MySQL [Y/n]"
const SCAN_POSTGRES = "Add PostgreSQL [Y/n]"
const SCAN_NO_SQL_DATABASE = "Add NoSQL database [Y/n]"
const SCAN_MONGODB = "Add MongoDB [Y/n]"
const SCAN_REDIS = "Add Redis [Y/n]"
const SCAN_REVERSE_PROXY = "Add reverse proxy (NGINX) [Y/n]"
const SCAN_API = "Add API [Y/n]"
const SCAN_REST = "Add REST API [Y/n]"
const SCAN_GRPC = "Add gRPC API [Y/n]"
const SCAN_GRAPHQL = "Add GraphQL [Y/n]"
const SCAN_ENTITIES = "Entities [User]"
